blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/surafel5509-del/2D-Game-Engine-Mobile#readme
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/surafel5509-del/2D-Game-Engine-Mobile/discussions
    about: Please ask and answer questions in the Discussions tab
